### ISSUE TITLE
Profie T support - Imaging Service Getting Failed 

### ISSUE THREAD

**Issue by Harini6999** [onvif/testspecs#20]
Hi,
I have to give profile T support for an ip camera. In ONVIF Conformance Test Tool,Imaging Service\Tampering Events* feature support and Imaging Service\Motion Alarm feature support steps are not getting passed.

referred document : https://www.onvif.org/wp-content/uploads/2021/06/ONVIF_Profiles_Conformance_Device_Test_Specification_21.06.pdf?ccc393&ccc393

as per this document, [page number - 102 section - 7] for imaging service, they are mentions to add function to GetServiceCapabilities , GetImagingSettings, GetOptions, SetImagingSettings apis. I have already added the code too. Even though step getting failed.

For GetEventProperties api, i have added RuleEngine (CellMotionDetector, TamperDetector) and VideoSource (MotionAlarm, GlobalSceneChange) responses for TopicSet, but the DUT did not return the specified topics.

How can i give a image service feature for T support to the device? is there any document to refer ?

Kindly help...Thanks in advance.

**Comment by SergeyBogdanov** [comment]
Hello,

Regards the question how to implement ONVIF Profile T on a camera and where to see the documentation for that.
The document you have mentioned is a technical document for Device Test Tool describing how the tool checks if ONVIF Profiles (including Profile T) is supported by DUT. I think this document is useful for troubleshooting in case if Profile T is implemented, but some small detail is detected by the Test Tool as incorrect. But for starting profile’s implementation this document is not very suitable.

More suitable documentation might be the profile specification. For Profile T it can be downloaded from the profile’s page: https://www.onvif.org/profiles/profile-t/. In the specification you may see references to the functionality necessary for device (the client’s part of functionality may be ignored as far as we are talking about Profile T for ONVIF Device). The functionality is mentioned in blocks that read, for example:

Function | Service | Requirement
GetServices | Device Management | M
GetServiceCapabilities | Device Management | M

In this case Requirement="M" means the method is mandatory and should be implemented. For implementation details you may go to network interfaces page: https://www.onvif.org/profiles/specifications/. On this page you may download the specification for necessary functionality and see details what needs to be implemented. 
For the block above, you may download the Core specification: https://www.onvif.org/specs/core/ONVIF-Core-Specification.pdf In the specification you may search for "GetServices" and "GetServiceCapabilities" methods and see the implementation details.

Also, you may use the Device Test Tool to help with implementation. You may declare the camera is supporting Profile T (by exposing Profile T’s scope) and then start conformance test in the Device Test Tool with the camera. The conformance process will fail, but you can switch to the Diagnostics tab and see which test cases are marked with red. For test case selected in the tree on left, the panel on right shows test case’s steps and error if any with some details. From the details you may see why the step is failed, you may fix this problem in camera’s implementation and run the test case one more time. (To save time you do not need to run whole conformance process every time. You may run test cases individually.) For additional detail you may click on the "Specification" tab on the left panel. The tool shows test specification for selected test case with details on test steps.

![test_cases](https://user-images.githubusercontent.com/86416327/162769701-39a07665-6b65-4e05-928f-f2f46f425c60.png)

Therefore, step-by-step you may make all test cases to pass. Eventually, the camera will be ready for Profile T conformance.

If you need more details, let me know. I will try to help.

Best regards,
Sergey Bogdanov
