### ISSUE TITLE
About "No Action element from namespace Addressing10 (http://www.w3.org/2005/08/addressing). Expected element with value: http://www.w3.org/2005/08/addressing/soap/fault. " error on "EVENT-3-1-19 v17 5.3.6 REALTIME PULLPOINT SUBSCRIPTION - UNSUBSCRIBE (NEGATIVE TEST)" test case of Onvif Device Test Tool V22.12

### ISSUE THREAD

**Issue by madhurao68** [onvif/testspecs#48]
Hi, We are facing an issue with developing the ONVIF device event service of profile S.
The device test tool keeps showing the error
`No Action element from namespace Addressing10 (http://www.w3.org/2005/08/addressing). Expected element with value: http://www.w3.org/2005/08/addressing/soap/fault.`  
on `EVENT-3-1-19 v17 5.3.6 REALTIME PULLPOINT SUBSCRIPTION - UNSUBSCRIBE (NEGATIVE TEST)` test case.
Here are the details of the requests and our response. Could you please guide us on how to fix this problem, thank you so much.
![FIRST](https://github.com/onvif/specs/assets/73811069/6528a1cb-cd0c-4253-ad38-f544ff16ddb0)

BTW, We also found a similar problem on StackOverflow but still met the same error...
https://stackoverflow.com/questions/58843206/error-while-raising-fault-from-the-dut-to-onvif-device-test-tool-in-the-test-cas

**Comment by fyspkid** [comment]
Hi 
I posted this question a few weeks ago. Thank @madhurao68  & @HansBusch for helping to transfer my question from spec forum to here.
I stuck on this issue for a long time. Could anyone guide me on this issue?
Thank you so much!!

**Comment by madhurao68** [comment]
Hi 
The 23.06 version of the test tool was released on the members portal very recently.  Work on 23.12 will commence in early August and this issue will be discussed with the test tool vendor and I will keep you posted. Thanks for your patience!

**Comment by fyspkid** [comment]
Hi madhurao68,
Thank you so much for the reply.
About the onvif device license certification, could we skip this item of the confomance test on V22.12 first?

thank you so much again and looking forward to your reply.

**Comment by HansBusch** [comment]
You probably wanted to write 23.06Hans on vacation
-------- Original message --------From: Madhu Rao ***@***.***> Date: 7/28/23  15:56  (GMT+01:00) To: onvif/testspecs ***@***.***> Cc: Hans Busch ***@***.***>, Mention ***@***.***> Subject: Re: [onvif/testspecs] About "No Action element from namespace
  Addressing10 (http://www.w3.org/2005/08/addressing). Expected element with
  value: http://www.w3.org/2005/08/addressing/soap/fault. " error on
  "EVENT-3-1-19 v17 5.3.6 REALTIME PULLPOINT SUBSCRIPTION - UNSUBSCRIBE
  (NEGATIVE TEST)" test case of Onvif Device Test Tool V22.12 (Issue #48) 
Hi
The 23.12 version of the test tool was released on the members portal very recently.  Work on 23.12 will commence in early August and this issue will be discussed with the test tool vendor and I will keep you posted. Thanks for your patience!

**Comment by fyspkid** [comment]
Hi madhurao68 & HansBusch
The identical error message appears when using the onvif device test tool V23.06 as well.
Could we skip this item of the confomance test on V22.12 & V23.06 first?

I appreciate you and look forward to hearing from you.

**Comment by madhurao68** [comment]
Hi,

The test EVENT-3-1-19 is an optional test and depends on the features implemented in the device under test. The test is executed in diagnostic mode only. So, this has no bearing on the conformance. You can uncheck the test during the diagnostic test run as well. 

To view the description just move the cursor on the test and you will get to see the importance of the test

![image](https://github.com/onvif/testspecs/assets/73811069/8efac629-325b-4d96-8c62-fc0cf9de56a6)



Hope this helps.

**Comment by LeslieHsia** [comment]
Hi madhura68,

I have a question for you,
we are going to make a Profile S product,
but I'm a little bit confused about the test items posted below,
I had read the Profile S spec and Profile Q spec,
these test items below are within the Profile Q scope,
but when I execute the conformance test, these items were checked and ready to run,
are these test items below within the Profile S scope?
Or these items are within the Profile Q scope?
![monitoring](https://github.com/onvif/testspecs/assets/16661577/e4a6ef28-8ae0-4503-922b-57a9a13ffce1)
If those test items are within Profile Q,
Can I skip these test items?

**Comment by madhurao68** [comment]
> Profile Q scope,

Hi LeslieHsia,

Profile Q is deprecated, and it is no longer possible to claim conformance for Profile Q.  The above tests come under device management and are mandatory if the specified feature is implemented by DUT.  So, you can uncheck them if the device does not support the features.
 
Hope this helps!

**Comment by fyspkid** [comment]
Hi madhura68,
Could you please guide us how to uncheck this monitoring events test cases on conformance test?
For example, are there any settings of conformance test could disable/uncheck these test cases? 
Or should we define anything in our GetService response code? We all set "false" in event device management event capability.
![Screenshot from 2023-08-15 10-08-47](https://github.com/onvif/testspecs/assets/15334934/56abf408-5d5b-44fa-80f1-539a74945b8c)

**Comment by LeslieHsia** [comment]
Hi madhura68,

Thanks for the rely,
it does help!

**Comment by madhurao68** [comment]
Hello,

Based on error DTT could not find wsa:Action tag itself (not the value inside the tag). So, the problem is with the tag itself or with related namespace. It is hard to check what exactly went wrong with it based on the screenshot, we need the text log for further analysis.

As for StackOverflow there is another issue. There is additional (") inside the Action tag and issue with the value:
"http://www.w3.org/2005/08/addressing/soap/fault"
instead of
http://www.w3.org/2005/08/addressing/soap/fault (without ")

**Comment by ram1994-web** [comment]
Hi,

I am facing this issue for test case EVENT 3-1-17 in the DTT Version 25.06 rev.93 as well. Can you confirm if it is resolved?
