### ISSUE TITLE
Failed to create filter for test" while testing onvif device tool

### ISSUE THREAD

**Issue by madhurao68** [onvif/testspecs#49]
Hi,
We meet a problem while testing test case EVENT-3-1-17 v14.12  of onvif device test tool V22.12.
There is an error in step 4, and the message is Failed to create filter for test which should be a CreatePullPointSubscription request from onvif device tool. However, it seems the onvif device tool does not send the request out and something about filter is wrong.
Here are the screenshots.
![254148404-164dd407-55e8-4a48-9c5e-e065821607e6](https://github.com/onvif/specs/assets/73811069/b80ee3bd-f2a6-4656-b869-ac9541741ba6)
![second](https://github.com/onvif/specs/assets/73811069/a534f0f8-50ea-400b-96ad-3664beba5c9a)
Could you help us with which step we did wrong?

**Comment by fyspkid** [comment]
Hi
I posted this question a few weeks ago. Thank @madhurao68 & @HansBusch for helping to transfer my question from spec forum to here.
It is the first time we meet this kind of error while using onvif device test tool. 
Should I try the latest version of onvif device test tool or anything I set up wrong?

Thank you so much

**Comment by madhurao68** [comment]
Hi
The 23.06 version of the test tool was released on the members portal very recently. Work on 23.12 will commence in early August and this issue will be discussed with the test tool vendor and I will keep you posted. Thanks for your patience!

**Comment by fyspkid** [comment]
Hi madhurao68,
Thank you so much for the reply.
About the onvif device license certification, could we skip this item of the confomance test on V22.12 first?

thank you so much again and looking forward to your reply.

**Comment by fyspkid** [comment]
Hi madhurao68 & HansBusch
The identical fail message appears when using the onvif device test tool V23.06 as well.
Could we skip this item of the confomance test on V22.12 & V23.06 first?

I appreciate you and look forward to hearing from you.

**Comment by madhurao68** [comment]
Hi
The test is run in diagnostic mode only (if supported by the device under test) so has no bearing on conformance. You can skip the test by unchecking the test in the diagnostic tab. Hope this helps.

**Comment by madhurao68** [comment]
@fyspkid could you attach xml log of this test case?

**Comment by fyspkid** [comment]
Hi madhurao68
Here is the xml log as we click "save all" on this EVENT-3-1-17 test case
[failed_to_create_filter.zip](https://github.com/onvif/testspecs/files/12309413/failed_to_create_filter.zip)

Thank you so much

**Comment by madhurao68** [comment]
Hello @fyspkid
The problem happens with devices that have empty topic set although it could be a bug in the DTT for this particular DUT configuration.
As mentioned earlier this test case is not in conformance because it is a negative test (most probably it always will be in diagnostic).

**Comment by fyspkid** [comment]
Hi @madhurao68 
I appreciate your kindly reply.
as you said, we perform a conformance test, and this test case is not marked.

Thank you so much.

**Comment by madhurao68** [comment]
Update:
Our test tool vendor checked the other test cases.  Device without Events Topics could not pass conformance in general. At least one shall be supported. So, it looks like this is a Device issue.
