### ISSUE TITLE
SEARCH-3-1-11-v19.12 FIND EVENTS - FORWARD AND BACKWARD SEARCH (SEACH ENDPOINTS INSIDE RECORDING ENDPOINTS) is failing even if in getservices "GeneralStartEvents" value is given false

### ISSUE THREAD

**Issue by yashavadan** [onvif/testspecs#50]
SEARCH-3-1-11-v19.12 FIND EVENTS - FORWARD AND BACKWARD SEARCH (SEACH ENDPOINTS INSIDE RECORDING ENDPOINTS) is failed with "No events found" reason.

In get service capabilities for **GeneralStartEvents** flag we have provided "**false**". Still Onvif Device Test Tool 23.06 is requesting Find Recoding with **IncludeStartState** value **true** during execution of SEARCH-3-1-11-v19.12 FIND EVENTS - FORWARD AND BACKWARD SEARCH (SEACH ENDPOINTS INSIDE RECORDING ENDPOINTS).

I have attached request response for reference.
[Issue.zip](https://github.com/onvif/testspecs/files/12287530/Issue.zip)

Note: During this testcase execution one recording was present in Devices under test.

Please help to solve this issue.

**Comment by madhurao68** [comment]
Hello,

If the device supports, events is mandatory irrespective of the GeneralStartEvents flag.
