### ISSUE TITLE
ConfigurationChanged and

### ISSUE THREAD

**Issue by Charley175** [onvif/testspecs#53]
Hello, I would like to ask the GetEventProperties interface what theme should be returned to support ConfigurationChanged and ProfileChanged, or where should I find the theme information for both events, thanks !!! 

Here is what the program now replies to the test tool, but is always told it is not supported.

        <tns1:MediaEvent>
          <ConfigurationChanged wstop:topic="true">
            <tt:MessageDescription IsProperty="true">
              <tt:Source>
                <tt:SimpleItemDescription Name="Token" Type="tt:ReferenceToken" />
                <tt:SimpleItemDescription Name="Type" Type="xsd:string" />
              </tt:Source>
            </tt:MessageDescription>
          </ConfigurationChanged>
        </tns1:MediaEvent>
        <tev:ProfileChanged wstop:topic="true">
          <tt:MessageDescription IsProperty="true">
            <tt:Source>
              <tt:SimpleItemDescription Name="Token" Type="tt:ReferenceToken" />
            </tt:Source>
          </tt:MessageDescription>
        </tev:ProfileChanged>
      </wstop:TopicSet>

**Comment by madhurao68** [comment]
The topic name **tns1:Media/ConfigurationChanged** means that in TopicSet there should be root tag **tns1:Media** and then tag **ConfigurationChanged** inside without namespace.

Topic structure is defined by WS-Topics standard: http://docs.oasis-open.org/wsn/wsn-ws_topics-1.3-spec-os.pdf.

**Example:**
```
       <tns1:Media xmlns:tns1="http://www.onvif.org/ver10/topics">
          <ProfileChanged wstop:topic="true" xmlns="" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1">
            <tt:MessageDescription IsProperty="false" xmlns:tt="http://www.onvif.org/ver10/schema">
              <tt:Source>
                <tt:SimpleItemDescription Name="Token" Type="tt:ReferenceToken" />
              </tt:Source>
            </tt:MessageDescription>
          </ProfileChanged>
          <ConfigurationChanged wstop:topic="true" xmlns="" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1">
            <tt:MessageDescription IsProperty="false" xmlns:tt="http://www.onvif.org/ver10/schema">
              <tt:Source>
                <tt:SimpleItemDescription Name="Token" Type="tt:ReferenceToken" />
                <tt:SimpleItemDescription Name="Type" Type="xsd:string" />
              </tt:Source>
            </tt:MessageDescription>
          </ConfigurationChanged>
        </tns1:Media>
```

**Comment by Charley175** [comment]
Thank you very much for your answer, which is very helpful to me.
