### ISSUE TITLE
Cannot get ConsumerReference.Address from wsnt__Subscribe

### ISSUE THREAD

**Issue by LeslieHsia** [onvif/testspecs#54]
Hi,
I got an issue when I run the "EVENT-2-1-17-v14.12 NOTIFY" test case of Onvif Device Test Tool(ver 23.06, rev. 96),
The Device Test Tool had sent the Subscribe request with the ConsumerReference.Address element but I cannot get the ConsumerReference.Address from wsnt__Subscribe(The screenshots as below),
![ConsumerReference_Address](https://github.com/onvif/testspecs/assets/16661577/5c448ed8-94ff-4e6e-bdef-e88083c9514c)
![ConsumerReference Address_NULL](https://github.com/onvif/testspecs/assets/16661577/77bfc23f-7ce7-4055-a037-afa885b45a33)

It seems that the "<a:Address>" element in in the wrong namesapce or has a namespace prefix when it should not be qualified with a namespace prefix.
Since "<a:Address>" is a qualied element, it could be that this isn't supposed to be qualified or the nsmaspace URI is the wrong one.
Do you have any advices for me to solve it ?
Can I remove the "a" prefix from the Device Test Tool?
If I can, how can I make it?

**Comment by madhurao68** [comment]
Subscribe request is defined by WS-BaseNotification specification: http://docs.oasis-open.org/wsn/wsn-ws_base_notification-1.3-spec-os.pdf.
You could find the details here at section **4.2 Subscribe**.
The content of Consumer reference is not from wsnt namespace, it is from wsa namespace (WS-Addressing).

The example of the message could be found at section **4.2.1 Example SOAP Encoding of the Subscribe Message Exchange** and it is the same with one sent by DTT.
