### ISSUE TITLE
About Onvif conformance test on JPEG on test items RTSS-1-1-34, RTSS-1-1-35, RTSS-1-1-36

### ISSUE THREAD

**Issue by fyspkid** [onvif/testspecs#60]
Hi,
We meet a problem on onvif conformance test with onvif devic test tool V.23.06.

We test Onvif test item about JPEG such as RTSS-1-1-34, RTSS-1-1-35, RTSS-1-1-36 and always fail in Waiting 12 frames to 1000ms.
It show only 1 or 0 frames captured.
<img width="819" alt="a" src="https://github.com/onvif/testspecs/assets/15334934/670be3f8-4b53-482d-96e1-e072d369656e">

<img width="812" alt="b" src="https://github.com/onvif/testspecs/assets/15334934/ebf7e382-a421-400f-8220-d8e6cd530403">

However, we play the streaming in other player such as VLC or ffplay, it show normal.
<img width="683" alt="c" src="https://github.com/onvif/testspecs/assets/15334934/76059938-0429-409a-bcce-c6498464967c">

What is the point for JPEG test item to capture frames?

Many thanks

**Comment by madhurao68** [comment]
Hello Could you please share the Wireshark logs for investigation? Thanks!

**Comment by SamForGit** [comment]
Hi madhurao68

update Wireshark log for test item RTSS-1-1-34.
```
Local computer IP: 192.168.1.190
Test Camera device: 192.168.1.100
```
[Capture_RTSS-1-1-34.zip](https://github.com/onvif/testspecs/files/12788068/Capture_RTSS-1-1-34.zip)

**Comment by madhurao68** [comment]
> Hi madhurao68
> 
> update Wireshark log for test item RTSS-1-1-34.
> 
> ```
> Local computer IP: 192.168.1.190
> Test Camera device: 192.168.1.100
> ```
> 
> [Capture_RTSS-1-1-34.zip](https://github.com/onvif/testspecs/files/12788068/Capture_RTSS-1-1-34.zip)

We will revert with the findings soon. Thanks for your patience!

**Comment by SamForGit** [comment]
Hi madhurao68

We are use Live555 to do mjpeg string.
We found that when we **_adjust OutPacketBuffer::maxSize from 3000000 to 64000_**
The RTSS-1-1-34 test item can pass but VLC play will show some green portion.
Why the test item will related to  OutPacketBuffer::maxSize?

```
 if (result.find("mjpeg") != std::string::npos)
	{
    
    *env << "\nCreate mjpeg options.\n";

    OutPacketBuffer::maxSize = 64000;

    char const* streamName = "streaming";

    char const* inputFileName = "/video";
 
    ServerMediaSession* sms
      = ServerMediaSession::createNew(*env, streamName, streamName,
				      descriptionString);
    
    sms->addSubsession(MJPEGVideoFileServerMediaSubsession
		       ::createNew(*env, inputFileName, reuseFirstSource));
....
```

update Wireshark log for test item RTSS-1-1-34.

```
Local computer IP: 192.168.1.190 
Test Camera device: 192.168.1.100

```
<img width="960" alt="Snap2" src="https://github.com/onvif/testspecs/assets/20531774/7ba04088-b5b0-48c3-8010-768f12415826">

<img width="960" alt="Snap1" src="https://github.com/onvif/testspecs/assets/20531774/dbbb4188-6ae2-4bc0-8f30-9f270b43399f">

**Comment by SamForGit** [comment]
Update update Wireshark log for test item RTSS-1-1-34.
[Capture02.zip](https://github.com/onvif/testspecs/files/12826891/Capture02.zip)

**Comment by madhurao68** [comment]
> Update update Wireshark log for test item RTSS-1-1-34. [Capture02.zip](https://github.com/onvif/testspecs/files/12826891/Capture02.zip)

Thanks for the update! We are investigating and will keep you posted. Thanks for your patience!

**Comment by madhurao68** [comment]
Hello,
Operation Delay is currently set to 1s. Could you please try to increase it to e.g. 60s?
Streaming test cases uses this timeout for waiting for packets. If this does not help, we will investigate the logs.
