### ISSUE TITLE
Errata argument for dtt_command_line tool results in error

### ISSUE THREAD

**Issue by skouzmine** [onvif/testspecs#78]
I attempt to execute `dtt_command_line` tool with errata argument providing path to the downloaded errata XML document.

```
"C:\Program Files (x86)\ONVIF\ONVIF Device Test Tool\23.12\dtt_command_line.exe" "c:\onvif\settings.xml" -e:"c:\onvif\DTT Errata 23.12.xml"
```

This gives me an error:
```
Errata Template loading failed: There is an error in XML document (1, 2).
Errata template file is not found or has incorrect format
```

I tried:
- different ways providing path to errata XML file
- different errata files
but it always results in the same error.

Works as expected without the errata argument.
All other arguments (`-tc` for example) work as expected.

Am I doing something incorrect?

Help would be greatly appreciated.

Thank you,
Stan

**Comment by madhurao68** [comment]
Hello,
We will revert back with the findings. Thanks for your patience.

**Comment by madhurao68** [comment]
Hello,
We would need the Errata xml file to analyze - looks like there is some formatting issue in the file. Thanks!

**Comment by skouzmine** [comment]
Thank you for the response.
These files are published in [https://members.onvif.org/member-tools](https://members.onvif.org/member-tools)
- [DTT-Errata-23.12.zip](https://github.com/onvif/testspecs/files/15229460/DTT-Errata-23.12.zip)
- [DTT-Errata-xml_v3-56.zip](https://github.com/onvif/testspecs/files/15229461/DTT-Errata-xml_v3-56.zip)

**Comment by madhurao68** [comment]
Hi,

We investigated and below are our findings:

The errata file cannot be directly used in the command line as a parameter. Unfortunately, the help file also does not have this information (and we plan to update the help file to reflect this).

The logic of using the errata file is as follows:

1. Test Operator has to get a list of faults that the DTT provides after conformance. In other words, a test operator just needs to have a list of errors that the DTT generates. DTT provide this information in a UI window:

![image](https://github.com/onvif/dtt/assets/118348082/aff207a5-449a-4324-9f85-a36e305e788c)

3. How to get this list:
  3.1 Run conformance in cmd mode without errata file. It will generate errata template.
  3.2 Run conformance in UI mode and copy a part with errata from a feature list and put it into an errata template.
  
4. A test operator has to update this errata template with numbers of errata and with description from the official errata file.

5. Now this file can be used in cmd mode. Numbers and descriptions will be taken from this file and put into the feature file and DoC.

Here is an errata template for cmd mode:

```xml
<?xml version="1.0"?>
<Errata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<Erratum>
		<Error>dn:NetworkVideoTransmitter feature was not defined</Error>
		<Number> </Number>
		<Description> </Description>
	</Erratum>  
	<Erratum>
		<Error>tds:Device feature was not defined</Error>
		<Number> </Number>
		<Description> </Description>
	</Erratum>
</Errata>
```

This is not a perfect solution as the user has to run conformance to get the lit of errors prior to execution of the command line tool. We will work on improving this in the upcoming versions.

**Comment by skouzmine** [comment]
Thank you very much.

Here is the errata XML file that works perfectly with the command line tool:
```xml
<?xml version="1.0"?>
<Errata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<Erratum>
		<Error>ANALYTICS-4-1-7-v21.06 MODIFY ANALYTICS MODULES (PARAMETERS WITH OPTIONS)</Error>
		<Number>65</Number>
		<Description>The tool does a string value comparison of the sensitivity values of the Analytics module generated by the device.</Description>
	</Erratum>
	<Erratum>
		<Error>ANALYTICS-4-1-8-v21.06 MODIFY ANALYTICS MODULES (PARAMETERS WITHOUT OPTIONS)</Error>
		<Number>66</Number>
		<Description>The test fails with internal error.</Description>
	</Erratum>
</Errata>
```
This file covers both open erratas for 23.12 version.

Looks like namespace declarations are redundant and file can be used without them.
